In [1]:
import pandas as pd 
import numpy as np

In [2]:
transport = pd.read_csv("../sources/transportation/passengers63-68.csv")

In [4]:
transport.isna().sum()

รูปแบบการเดินทาง       0
วัตถุประสงค์           0
สาธารณะ/ส่วนบุคคล      0
หน่วยงาน               0
ยานพาหนะ/ท่า           0
วันที่                 0
หน่วย                  0
ปริมาณ               196
dtype: int64

In [5]:
transport['ยานพาหนะ/ท่า'].unique()

array(['รถ ขบส. และ รถร่วม', 'รถยนต์เฉพาะ 4 ล้อ (10 จุดสำรวจ)',
       'รถยนต์ทุกประเภท (10 จุดสำรวจ)', 'รถยนต์เฉพาะ 4 ล้อ (ทางด่วน)',
       'รถยนต์ทุกประเภท (ทางด่วน)', 'รถเมล์ ขสมก.', 'รถร่วม (หมวด 1)',
       'เรือด่วนเจ้าพระยา', 'เรือคลองแสนแสบ', 'เรือภูมิภาค', 'รถไฟ',
       'รถไฟฟ้าสายสีน้ำเงิน', 'รถไฟฟ้าสายสีม่วง', 'รถไฟฟ้า ARL',
       'รถไฟฟ้า BTS', 'ท่าอากาศยานสุวรรณภูมิ', 'ท่าอากาศยานดอนเมือง',
       'ท่าอากาศอื่น ๆ ของ ทอท.', 'ท่าอากาศยานภูมิภาค',
       'ท่าอากาศยานสุวรรณภูมิ ขาเข้าประเทศ',
       'ท่าอากาศยานสุวรรณภูมิ ขาออกประเทศ',
       'ท่าอากาศยานดอนเมือง ขาเข้าประเทศ',
       'ท่าอากาศยานดอนเมือง ขาออกประเทศ',
       'ท่าอากาศอื่น ๆ ของ ทอท.ขาเข้าประเทศ',
       'ท่าอากาศอื่น ๆ ของ ทอท. ขาออกประเทศ',
       'ท่าอากาศยานภูมิภาค ขาเข้าประเทศ',
       'ท่าอากาศยานภูมิภาค ขาออกประเทศ', 'รถหมวด 3', 'รถหมวด 4',
       'รถ บขส. ขาเข้าประเทศ', 'รถ บขส. ขาออกประเทศ', 'รถไฟ ขาเข้าประเทศ',
       'รถไฟ ขาออกประเทศ', 'ท่าเรือด่านชายแดน ขาออกประเทศ',
       'รถเอกชนเส้นปฏิรูป (หมวด 1)', 'ท่าเรือด่านชายแดน ขาเข้าประเทศ',
       'เรือข้ามฟากเจ้าพระยา', 'เรือไฟฟ้าเจ้าพระยา', 'รถไฟสายสีแดง',
       'ท่าอากาศยานอู่ตะเภา', 'ท่าอากาศยานสมุย', 'รถ บขส. และ รถร่วม',
       'รถไฟฟ้าสายสีแดง', 'ท่าอากาศยานอื่น ๆ ของ ทอท. ขาเข้าประเทศ',
       'ท่าอากาศยานอื่น ๆ ของ ทอท. ขาออกประเทศ', 'รถไฟฟ้าสายสีเหลือง',
       'รถไฟฟ้าสายสีชมพู', 'รถไฟฟ้าสายสีชมพูู'], dtype=object)

In [6]:
transport['ยานพาหนะ/ท่า'] = transport['ยานพาหนะ/ท่า'].replace({
    'รถไฟฟ้าสายสีชมพูู': 'รถไฟฟ้าสายสีชมพู',  # แก้ไขการพิมพ์ผิด
    'รถไฟสายสีแดง': 'รถไฟฟ้าสายสีแดง'  # ปรับให้เป็นรูปแบบเดียวกัน
})

In [8]:
# ตรวจสอบค่าที่มีในคอลัมน์
print(transport['ยานพาหนะ/ท่า'].unique())

# กรองเฉพาะข้อมูลรถไฟฟ้า
allowed_rail = [
    'รถไฟฟ้าสายสีน้ำเงิน',
    'รถไฟฟ้าสายสีม่วง',
    'รถไฟฟ้า ARL',
    'รถไฟฟ้า BTS',
    'รถไฟฟ้าสายสีแดง',
    'รถไฟฟ้าสายสีเหลือง',
    'รถไฟฟ้าสายสีชมพู'
]
transport = transport[transport['ยานพาหนะ/ท่า'].isin(allowed_rail)].reset_index(drop=True)

# ตรวจสอบค่าหลังการกรอง
transport['ยานพาหนะ/ท่า'].unique()

['รถ ขบส. และ รถร่วม' 'รถยนต์เฉพาะ 4 ล้อ (10 จุดสำรวจ)'
 'รถยนต์ทุกประเภท (10 จุดสำรวจ)' 'รถยนต์เฉพาะ 4 ล้อ (ทางด่วน)'
 'รถยนต์ทุกประเภท (ทางด่วน)' 'รถเมล์ ขสมก.' 'รถร่วม (หมวด 1)'
 'เรือด่วนเจ้าพระยา' 'เรือคลองแสนแสบ' 'เรือภูมิภาค' 'รถไฟ'
 'รถไฟฟ้าสายสีน้ำเงิน' 'รถไฟฟ้าสายสีม่วง' 'รถไฟฟ้า ARL' 'รถไฟฟ้า BTS'
 'ท่าอากาศยานสุวรรณภูมิ' 'ท่าอากาศยานดอนเมือง' 'ท่าอากาศอื่น ๆ ของ ทอท.'
 'ท่าอากาศยานภูมิภาค' 'ท่าอากาศยานสุวรรณภูมิ ขาเข้าประเทศ'
 'ท่าอากาศยานสุวรรณภูมิ ขาออกประเทศ' 'ท่าอากาศยานดอนเมือง ขาเข้าประเทศ'
 'ท่าอากาศยานดอนเมือง ขาออกประเทศ' 'ท่าอากาศอื่น ๆ ของ ทอท.ขาเข้าประเทศ'
 'ท่าอากาศอื่น ๆ ของ ทอท. ขาออกประเทศ' 'ท่าอากาศยานภูมิภาค ขาเข้าประเทศ'
 'ท่าอากาศยานภูมิภาค ขาออกประเทศ' 'รถหมวด 3' 'รถหมวด 4'
 'รถ บขส. ขาเข้าประเทศ' 'รถ บขส. ขาออกประเทศ' 'รถไฟ ขาเข้าประเทศ'
 'รถไฟ ขาออกประเทศ' 'ท่าเรือด่านชายแดน ขาออกประเทศ'
 'รถเอกชนเส้นปฏิรูป (หมวด 1)' 'ท่าเรือด่านชายแดน ขาเข้าประเทศ'
 'เรือข้ามฟากเจ้าพระยา' 'เรือไฟฟ้าเจ้าพระยา' 'รถไฟฟ้าสายสีแดง'
 'ท่าอากาศยานอู่ตะเภา' 'ท่าอากาศยานสมุย' 'รถ บขส. และ รถร่วม'
 'ท่าอากาศยานอื่น ๆ ของ ทอท. ขาเข้าประเทศ'
 'ท่าอากาศยานอื่น ๆ ของ ทอท. ขาออกประเทศ' 'รถไฟฟ้าสายสีเหลือง'
 'รถไฟฟ้าสายสีชมพู']

array(['รถไฟฟ้าสายสีน้ำเงิน', 'รถไฟฟ้าสายสีม่วง', 'รถไฟฟ้า ARL',
       'รถไฟฟ้า BTS', 'รถไฟฟ้าสายสีแดง', 'รถไฟฟ้าสายสีเหลือง',
       'รถไฟฟ้าสายสีชมพู'], dtype=object)

In [13]:
transport.drop(columns=['รูปแบบการเดินทาง', 'วัตถุประสงค์', 'สาธารณะ/ส่วนบุคคล', 'หน่วยงาน', 'หน่วย'], inplace=True)

In [17]:
transport[transport['ยานพาหนะ/ท่า'] == 'รถไฟฟ้าสายสีชมพู']

           ยานพาหนะ/ท่า      วันที่   ปริมาณ
7271   รถไฟฟ้าสายสีชมพู  2024-02-25  29757.0
7278   รถไฟฟ้าสายสีชมพู  2024-02-26  28278.0
7285   รถไฟฟ้าสายสีชมพู  2024-02-27  52505.0
7292   รถไฟฟ้าสายสีชมพู  2024-02-28  52426.0
7299   รถไฟฟ้าสายสีชมพู  2024-02-29  53949.0
...                 ...         ...      ...
11139  รถไฟฟ้าสายสีชมพู  2025-08-30  53569.0
11146  รถไฟฟ้าสายสีชมพู  2025-08-31  45400.0
11153  รถไฟฟ้าสายสีชมพู  2025-09-01  75159.0
11160  รถไฟฟ้าสายสีชมพู  2025-09-02  75584.0
11167  รถไฟฟ้าสายสีชมพู  2025-09-03  75169.0

[558 rows x 3 columns]

In [15]:
transport.to_csv('../sources/transportation/daily_transport_rail.csv', index = False)